#!/bin/bash -l
#SBATCH -A dp092
#SBATCH -p cosma7-pauper
#SBATCH --nodes 1
### NB cosma6 has 16 cores per node so product of these = 16
#SBATCH --ntasks-per-node=8
#SBATCH --cpus-per-task=2
#SBATCH -o output_file.%J.out
#SBATCH -e error_file.%J.err
#
#SBATCH -t 1:00:00
#SBATCH -J ICS
#SBATCH --exclusive
#SBATCH --mail-type=NONE             # notifications for job done & fail
#SBATCH --mail-user=james.bamber@physics.ox.ac.uk
module purge
#load the modules used to build your program.
module load intel_comp/2019 intel_mpi/2019 parallel_hdf5/1.10.3
export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
# Run the program
export application=/cosma/home/dp174/dc-bamb1/InitialConditionSolver_complex/Main_PoissonSolver3d.Linux.64.mpiicpc.ifort.OPTHIGH.MPI.OPENMPCC.ex
mpirun -np $SLURM_NTASKS ${application} ../params.txt
